#!/usr/bin/env bash
# scrub.sh — P-track anonymization before blind rating.
#
# Implements harness/party/scoring-rubric.md § SCRUB PROTOCOL. Raters see only
# the scrubbed deliverable under a neutral label (Output A/B/C/D); the arm↔label
# map is sealed in the run-task's _scoring/ dir, revealed after scoring.
#
# Subcommands:
#   scan  <file>                       grep the tell-list; report hits (exit 1 if any)
#   seal  <task> <arm> <run> <label>   stage a scrubbed copy as Output <label>:
#                                        copy artifacts/decision.md → _scoring/scrubbed/output-<label>.md,
#                                        apply SAFE auto-strips, re-scan (must be CLEAN
#                                        or pass --force after a manual edit), sha256,
#                                        append arm↔label↔sha to the sealed map.
#   map   <task>                       print the sealed map (operator-only; NOT for raters)
#
# SAFE auto-strips (won't mangle prose): BMAD frontmatter / doc-numbering lines,
# _bmad-output path strings, "Claude Code" / skill-name / thinking-block remnants,
# leading/trailing template fences. Persona names embedded in prose (the A4 risk)
# are NOT auto-replaced — the scan FLAGS them and the operator hand-scrubs, so we
# never corrupt a legitimately-occurring word. [ASSUMPTION] tags are KEPT (all arms
# share them by protocol — not a tell).

set -euo pipefail
HARNESS="${SDD_BENCH_HARNESS:-$HOME/dev/sdd-bench}"

# The tell-list (rubric § Scrub grep list — keep in sync; additions are logged).
# v2 (P-track P1/P5/P8 scoring): word-boundary the persona/role names so common
# substrings don't false-positive (e.g. Mary inside "primary"/"summary", which the
# P5 materials use heavily). Unambiguous tells (bmad, party-mode, claude-*, paths)
# stay as substrings.
TELLS='\b(Mary|John|Sally|Winston|James|Linus|Amelia|Bob|Paige|BMad)\b|bmad|party.?mode|\b(panel|roundtable|facilitator)\b|analyst agent|architect agent|Claude Code|claude-(fable|opus|sonnet)|_bmad-output|\.claude/'

die() { echo "ERROR: $*" >&2; exit 2; }

scan() { # <file> → prints hits, returns 1 if any
  local f="$1"
  if grep -nEi "$TELLS" "$f"; then return 1; else echo "CLEAN (no tells)"; return 0; fi
}

safe_strip() { # in-place safe auto-strips on a staged file
  local f="$1"
  # Drop whole lines that are pure BMAD/tool template artifacts (conservative:
  # only lines that are clearly machinery, not prose).
  sed -i '' -E \
    -e '/_bmad-output/d' \
    -e '/^<!-- *BMAD/d' \
    -e '/^_Generated by .*BMAD/Id' \
    -e '/Powered by BMAD/Id' \
    "$f" || true
}

cmd="${1:-}"; shift || true
case "$cmd" in
  scan)
    [ -f "${1:-}" ] || die "usage: scrub.sh scan <file>"
    scan "$1" ;;

  seal)
    TASK="${1:-}"; ARM="${2:-}"; RUN="${3:-}"; LABEL="${4:-}"; FORCE="${5:-}"
    [ -n "$TASK" ] && [ -n "$ARM" ] && [ -n "$RUN" ] && [ -n "$LABEL" ] \
      || die "usage: scrub.sh seal <task> <arm> <run> <label> [--force]"
    # Deliverable = the single top-level .md in artifacts/ (decision.md / threat-model.md /
    # roadmap.md / root-cause.md …) — auto-detected so this works across tasks.
    SRC=$(ls "$HARNESS/runs/party/$TASK/$ARM/run-$RUN/artifacts/"*.md 2>/dev/null | head -1)
    [ -n "$SRC" ] && [ -f "$SRC" ] || die "deliverable .md not found in runs/party/$TASK/$ARM/run-$RUN/artifacts/"
    SCDIR="$HARNESS/runs/party/$TASK/_scoring"
    mkdir -p "$SCDIR/scrubbed"
    DST="$SCDIR/scrubbed/output-$LABEL.md"
    if [ "$FORCE" = "--force" ] && [ -f "$DST" ]; then
      echo "(--force: keeping hand-scrubbed $DST, not re-copying from source)"
    else
      cp "$SRC" "$DST"
      safe_strip "$DST"
    fi
    echo "=== post-strip scan of output-$LABEL.md ==="
    if ! scan "$DST"; then
      if [ "$FORCE" != "--force" ]; then
        echo "ABORT: residual tells in $DST — hand-scrub it, then re-run with --force." >&2
        exit 1
      fi
      echo "WARN: tells remain but --force given (operator hand-scrubbed)."
    fi
    SHA=$(shasum -a 256 "$DST" | awk '{print $1}')
    MAP="$SCDIR/scrub-map.sealed.md"
    [ -f "$MAP" ] || { echo "# SEALED arm↔label map — $TASK (NOT for raters; reveal after scoring)"; echo; echo "| Label | Arm | run | sha256 (scrubbed) |"; echo "|---|---|---|---|"; } > "$MAP"
    echo "| $LABEL | $ARM | $RUN | $SHA |" >> "$MAP"
    echo "SEALED: Output $LABEL ← $ARM/run-$RUN  sha256=$SHA"
    echo "  rater input: $DST"
    echo "  sealed map:  $MAP" ;;

  map)
    TASK="${1:-}"; [ -n "$TASK" ] || die "usage: scrub.sh map <task>"
    cat "$HARNESS/runs/party/$TASK/_scoring/scrub-map.sealed.md" ;;

  *)
    sed -n '2,30p' "$0" | sed 's/^# \?//'; exit 1 ;;
esac
